name: Update snake animation

on:
  pull_request:
  push:
    branches:
    - master

jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest
    
    steps:
      # Snake Animation
      - uses: Platane/snk@master
        with:
          github_user_name: ${{ github.repository_owner }}
          gif_out_path: dist/github-snake.gif
